# Generated by Django 5.1.5 on 2025-06-10 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0009_user_password'),
        ('BlinkRate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blinkrate',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.user'),
            preserve_default=False,
        ),
    ]
