# Generated by Django 5.1.5 on 2025-06-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0009_user_password'),
        ('BlinkRate', '0002_blinkrate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blinkrate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseInfo.user'),
        ),
    ]
