# Generated by Django 5.1.5 on 2025-05-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0002_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test_type',
            field=models.CharField(choices=[('myopia', 'Myopia'), ('glaucoma', 'Glaucoma')], max_length=100),
        ),
    ]
