# Generated by Django 5.1.5 on 2025-05-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0003_alter_testresult_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='final_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
