# Generated by Django 5.1.5 on 2025-05-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0005_alter_testresult_result_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='final_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
