# Generated by Django 5.1.5 on 2025-05-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0007_colorvisiontest_colorvisionplateresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ph_Number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
