# Generated by Django 5.1.5 on 2025-05-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0008_alter_user_ph_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
