# Generated by Django 5.1 on 2025-06-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0009_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryEyeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osdi_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('severity', models.CharField(choices=[('Normal', 'Normal'), ('Mild', 'Mild Dry Eye Disease'), ('Moderate', 'Moderate Dry Eye Disease'), ('Severe', 'Severe Dry Eye Disease')], max_length=20)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dryeye_results', to='BaseInfo.user')),
            ],
        ),
    ]
