# Generated by Django 5.1 on 2025-06-20 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0010_dryeyeresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlaucomaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_correct', models.IntegerField()),
                ('severity', models.CharField(choices=[('Normal', 'Normal Vision'), ('Mild Defect', 'Mild Peripheral Vision Defect'), ('Moderate Defect', 'Moderate Peripheral Vision Defect'), ('Severe Defect', 'Severe Peripheral Vision Defect')], max_length=20)),
                ('viewing_distance', models.IntegerField(default=60)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glaucoma_results', to='BaseInfo.user')),
            ],
        ),
    ]
