# Generated by Django 5.1 on 2025-06-21 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0011_glaucomaresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyopiaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_eye_diopter', models.FloatField()),
                ('right_eye_diopter', models.FloatField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myopia_results', to='BaseInfo.user')),
            ],
        ),
    ]
