# Generated by Django 5.1 on 2025-07-14 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0012_myopiaresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='BaseInfo.user')),
            ],
        ),
        migrations.CreateModel(
            name='OphthalmicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_item', models.CharField(choices=[('glaucoma', 'Glaucoma'), ('retinal_detachment', 'Retinal detachment'), ('glasses_use', 'Glasses use'), ('eye_disease', 'Eye disease'), ('eye_surgery', 'Eye surgery'), ('uveitis', 'Uveitis'), ('retinal_laser', 'Retinal laser treatment'), ('contact_lens', 'Contact lens use'), ('other', 'Other')], max_length=50)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ophthalmic_histories', to='BaseInfo.patienthistory')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_item', models.CharField(choices=[('glaucoma', 'Glaucoma'), ('keratoconus', 'Keratoconus'), ('myopia', 'Myopia'), ('other', 'Other')], max_length=50)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_histories', to='BaseInfo.patienthistory')),
            ],
        ),
        migrations.CreateModel(
            name='DrugAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_type', models.CharField(choices=[('antimicrobial_agents', 'Antimicrobial agents'), ('antifungal_agents', 'Antifungal agents'), ('eye_drops', 'Eye drops'), ('other', 'Other')], max_length=50)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_allergies', to='BaseInfo.patienthistory')),
            ],
        ),
        migrations.CreateModel(
            name='ContactAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_type', models.CharField(choices=[('alcohol', 'Alcohol'), ('betadine', 'Betadine'), ('other', 'Other')], max_length=50)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_allergies', to='BaseInfo.patienthistory')),
            ],
        ),
        migrations.CreateModel(
            name='ChiefComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(choices=[('blurry_vision', 'Blurry vision'), ('diminution_vision', 'Diminution of vision'), ('pain', 'Pain'), ('irritation', 'Irritation'), ('redness', 'Redness'), ('injury_trauma', 'Injury / Trauma'), ('watering', 'Watering'), ('discharge', 'Discharge'), ('dryness', 'Dryness'), ('itching', 'Itching'), ('foreign_body', 'Foreign body sensation'), ('deviation_squint', 'Deviation / Squint'), ('headache_strain', 'Headache / Strain'), ('swelling', 'Swelling'), ('burning_sensation', 'Burning sensation'), ('discoloration', 'Discoloration of eye'), ('other', 'Other')], max_length=50)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chief_complaints', to='BaseInfo.patienthistory')),
            ],
        ),
        migrations.CreateModel(
            name='SystemicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_item', models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('alcoholism', 'Alcoholism'), ('smoking_tobacco', 'Smoking tobacco'), ('cardiac_disorder', 'Cardiac disorder'), ('steroid_intake', 'Steroid intake'), ('drug_abuse', 'Drug abuse'), ('hiv_aids', 'HIV / AIDS'), ('tuberculosis', 'Tuberculosis'), ('asthma', 'Asthma'), ('cns_disorder', 'CNS disorder / Stroke'), ('hyperthyroidism', 'Hyperthyroidism'), ('hypothyroidism', 'Hypothyroidism'), ('hepatitis_cirrhosis', 'Hepatitis / Cirrhosis'), ('renal_disorder', 'Renal disorder'), ('acidity', 'Acidity'), ('on_insulin', 'On insulin'), ('blood_thinners', 'On aspirin / blood thinners'), ('consanguinity', 'Consanguinity'), ('thyroid_disorder', 'Thyroid disorder'), ('chewing_tobacco', 'Chewing tobacco'), ('chronic_kidney', 'Chronic kidney disease'), ('rheumatoid_arthritis', 'Rheumatoid arthritis'), ('other', 'Other')], max_length=50)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systemic_histories', to='BaseInfo.patienthistory')),
            ],
        ),
    ]
