# Generated by Django 5.1.5 on 2025-07-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BaseInfo", "0013_patienthistory_ophthalmichistory_familyhistory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myopiaresult",
            name="left_eye_diopter",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="myopiaresult",
            name="right_eye_diopter",
            field=models.CharField(max_length=10),
        ),
    ]
