# Generated by Django 5.1 on 2025-08-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseInfo', '0014_alter_myopiaresult_left_eye_diopter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
