# Generated by Django 5.1.5 on 2025-06-13 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseInfo', '0010_dryeyeresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_eye', models.ImageField(upload_to='')),
                ('right_eye', models.ImageField(upload_to='')),
                ('responses', models.CharField(max_length=50000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eye_Images', to='BaseInfo.user')),
            ],
        ),
    ]
